language: node_js
node_js:
  - "node"

addons:
  ssh_known_hosts: build.archlinuxcn.org

script:
  - sed -i 's#http://localhost:22333#https://build.archlinuxcn.org#g' src/main.js
  - npm install
  - npm run build

before_deploy:
  - openssl aes-256-cbc -K $encrypted_b9fe8a84dafa_key -iv $encrypted_b9fe8a84dafa_iv -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa

deploy:
  - provider: script
    skip_cleanup: true
    script: cat .deploylist | xargs tar -cJf - | ssh a-wing@build.archlinuxcn.org 'mkdir -p .srv/tmp/kiss2ui && cd .srv/tmp/kiss2ui && tar -xJf - && cp -r * /srv/packages/ && cd .. && rm -r kiss2ui'
    on:
      branch: master

